### PR TITLE
fix: Loop until all sales from timeframe are retrieved

### LINKED ISSUE #66: Loop through all sales in the past 2 days to prepare trendings
Right now, the query is using the default `first` parameter so it's only getting the latest 20 sales, which can have repeated items in them. We need to get ALL the sales that happened in the 2 days and loop through all of them to analyze which are the trending items based on them.

### PR DESCRIPTION
**Pull request by juanmahidalgo**
Closes #66

### CODE REVIEW

File: src/ports/trendings/component.ts [hunk 1]
```diff
@@ -1,53 +1,83 @@
...
 export const VOLUME_CUT = 0.4
 
 export function createTrendingsComponent(
-  salesComponent: IMergerComponent<Sale, SaleFilters, SaleSortBy>,
+  collectionsSubgraph: ISubgraphComponent,
   itemsComponent: IItemsComponent
 ): ITrendingsComponent {
+  async function fetchTrendingSales(skip: number) {
+    const query = getTrendingsQuery(
+      { from: getDateXDaysAgo(2).getTime(), first: 1000, skip },
```
Comment (cazala) [inline src/ports/trendings/component.ts:24]: This is more of a question than a change request, but why did we change to 2 days instead of 1? Doesn't the UI say `last 24hs`?

**Review by cazala — APPROVED** [review]
🙌
