### PR TITLE
fix: creators var will always have value and fallbacks network to Matic

### LINKED ISSUE #338: catalog default request is not bringing Ethereum results
There's a bug that is preventing the Ethereum items to be returned when asking for the items in the marketplace browse page. This is due to a check that was added recently and it's always fallbacking to `MATIC` instead of both networks. 
```
const sources = (
        network
          ? [network]
          : creator
          ? [Network.MATIC]
          : [Network.ETHEREUM, Network.MATIC]
```
the `creator` variable is an array, so it will never be falsy, so it always returns `MATIC`.

### PR DESCRIPTION
**Pull request by juanmahidalgo**
Closes #338

### CODE REVIEW

File: src/ports/catalog/component.ts [hunk 1]
```diff
@@ -26,26 +23,12 @@ export function createCatalogComponent(options: {
...
-    const collectionsChainId = getCollectionsChainId()
+    const { network } = filters
     let catalogItems: Item[] = []
     let total = 0
     const client = await database.getPool().connect()
     try {
-      const sources = (
-        network
-          ? [network]
-          : creator
```
Comment (juanmahidalgo) [inline src/ports/catalog/component.ts:39]: the issue was in this line, `creator` won't ever be falsy since it's an array (either empty or with a list of adddresses)

File: src/tests/ports/catalog-utils.spec.ts [hunk 2]
```diff
@@ -0,0 +1,50 @@
...
+  it('should return sources for a specific network', () => {
+    const filters = { network: Network.ETHEREUM }
+    const sources = getQuerySources(filters)
+    expect(sources).toEqual({
+      [Network.ETHEREUM]: getSubgraphNameForNetwork(
+        Network.ETHEREUM,
+        marketplaceChainId as ChainId
+      ),
+    })
+  })
```
Comment (LautaroPetaccio) [inline src/tests/ports/catalog-utils.spec.ts:23]: Would you mind writing the tests using a describe to identify the context of the execution of the test?
```suggestion
let filters: Filters (don't know the type)
let sources: Sources

describe('when filtering by network', () => {
 beforeEach(() => {
  filters = { network: Network.ETHEREUM }
  sources = getQuerySources(filters)
 })

  it('should return sources for the provided network', () => {
    expect(sources).toEqual({
      [Network.ETHEREUM]: getSubgraphNameForNetwork(
        Network.ETHEREUM,
        marketplaceChainId as ChainId
      ),
    })
  })
})
```

**Review by LautaroPetaccio — APPROVED** [review]
The code looks great 👍 
I'm leaving a comment to refactor the tests if you find it right.
